<!-- Declare hyper links to DataSet, Autors GitHub, and the project GitHub -->
[DataSet]: https://www.kaggle.com/itachi9604/disease-symptom-description-dataset?select=dataset.csv
[Denis]: https://github.com/Denloob/Denloob
[Itai]: None
[Yoav]: None

# About the project
#### Project theme:
Disease clasification based on symptoms.
#### Made by
[Denis], [Itai] and [Yoav]

DM Den_loob#2209 using [discord](https://discord.com/) or using github to get in touch with the project.
#### School:
Israel, Haifa, Bosmat Hahadas (New Bosmat)

<!--
TODO explain the project, tech it uses, our motivation and other things from https://docs.google.com/document/d/1EN6CdHNkYj2LZxchPIlIdCTKsZ0pjpfetIv9MitxnLI/edit
-->

# TODO
_sorted by importance_
1. Make so same symptom have same num value when encoded so it would be easier to mix the data
1. Mix the symptoms order when training and testing
1. Find more data and add it to the data set
1. Make the ui

# Study of the data

In [1]:
import pandas as pd
df = pd.read_csv('data/dataset.csv')
display(df.info())
display(df.describe())
display(df)
print(f'{df.shape=}')
print(f'unique values of 17 disease withoud nan: {df["Symptom_17"].dropna().unique()}')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4920 entries, 0 to 4919
Data columns (total 18 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Disease     4920 non-null   object
 1   Symptom_1   4920 non-null   object
 2   Symptom_2   4920 non-null   object
 3   Symptom_3   4920 non-null   object
 4   Symptom_4   4572 non-null   object
 5   Symptom_5   3714 non-null   object
 6   Symptom_6   2934 non-null   object
 7   Symptom_7   2268 non-null   object
 8   Symptom_8   1944 non-null   object
 9   Symptom_9   1692 non-null   object
 10  Symptom_10  1512 non-null   object
 11  Symptom_11  1194 non-null   object
 12  Symptom_12  744 non-null    object
 13  Symptom_13  504 non-null    object
 14  Symptom_14  306 non-null    object
 15  Symptom_15  240 non-null    object
 16  Symptom_16  192 non-null    object
 17  Symptom_17  72 non-null     object
dtypes: object(18)
memory usage: 692.0+ KB

None

,Disease,Symptom_1,Symptom_2,Symptom_3,Symptom_4,Symptom_5,Symptom_6,Symptom_7,Symptom_8,Symptom_9,Symptom_10,Symptom_11,Symptom_12,Symptom_13,Symptom_14,Symptom_15,Symptom_16,Symptom_17
count,4920,4920,4920,4920,4572,3714,2934,2268,1944,1692,1512,1194,744,504,306,240,192,72
unique,41,34,48,54,50,38,32,26,21,22,21,18,11,8,4,3,3,1
top,AIDS,vomiting,vomiting,fatigue,high_fever,headache,nausea,abdominal_pain,abdominal_pain,yellowing_of_eyes,yellowing_of_eyes,irritability,malaise,malaise,chest_pain,chest_pain,blood_in_sputum,muscle_pain
freq,120,822,870,726,378,348,390,264,276,228,198,120,126,72,96,144,72,72

,Disease,Symptom_1,Symptom_2,Symptom_3,Symptom_4,Symptom_5,Symptom_6,Symptom_7,Symptom_8,Symptom_9,Symptom_10,Symptom_11,Symptom_12,Symptom_13,Symptom_14,Symptom_15,Symptom_16,Symptom_17
0,Fungal infection,itching,skin_rash,nodal_skin_eruptions,dischromic _patches,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Fungal infection,skin_rash,nodal_skin_eruptions,dischromic _patches,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Fungal infection,itching,nodal_skin_eruptions,dischromic _patches,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Fungal infection,itching,skin_rash,dischromic _patches,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Fungal infection,itching,skin_rash,nodal_skin_eruptions,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4915,(vertigo) Paroymsal Positional Vertigo,vomiting,headache,nausea,spinning_movements,loss_of_balance,unsteadiness,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4916,Acne,skin_rash,pus_filled_pimples,blackheads,scurring,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4917,Urinary tract infection,burning_micturition,bladder_discomfort,foul_smell_of urine,continuous_feel_of_urine,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4918,Psoriasis,skin_rash,joint_pain,skin_peeling,silver_like_dusting,small_dents_in_nails,inflammatory_nails,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4919,Impetigo,skin_rash,high_fever,blister,red_sore_around_nose,yellow_crust_ooze,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

df.shape=(4920, 18)
unique values of 17 disease withoud nan: [' muscle_pain']

* Dataset has 4920 rows and 18 columns, one of them is Diseases and others are Symptoms.
* Symptoms 1-3 are allways not null.
* If disease has sympotm in column X all the previous symptoms are not null.
* Symtoms 4-17 are nullable.
* Most (>50%) of diseases have also symtopms 4-6.
* Also a litlle less than 50% of diseases also have symptom 7.
* If a disease has symptom 17, it is always muscle_pain.

In [2]:
# convert the entire dataset to unic numeric values

from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

numeric_df = df.copy()
for i, colomn in enumerate(numeric_df.columns):
    numeric_df[colomn] = le.fit_transform(df[colomn])

display(numeric_df.info())
display(numeric_df.describe())
display(numeric_df)
print(f'{numeric_df.shape=}')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4920 entries, 0 to 4919
Data columns (total 18 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Disease     4920 non-null   int32
 1   Symptom_1   4920 non-null   int32
 2   Symptom_2   4920 non-null   int32
 3   Symptom_3   4920 non-null   int32
 4   Symptom_4   4920 non-null   int32
 5   Symptom_5   4920 non-null   int32
 6   Symptom_6   4920 non-null   int32
 7   Symptom_7   4920 non-null   int32
 8   Symptom_8   4920 non-null   int32
 9   Symptom_9   4920 non-null   int32
 10  Symptom_10  4920 non-null   int32
 11  Symptom_11  4920 non-null   int32
 12  Symptom_12  4920 non-null   int32
 13  Symptom_13  4920 non-null   int32
 14  Symptom_14  4920 non-null   int32
 15  Symptom_15  4920 non-null   int32
 16  Symptom_16  4920 non-null   int32
 17  Symptom_17  4920 non-null   int32
dtypes: int32(18)
memory usage: 346.1 KB

None

,Disease,Symptom_1,Symptom_2,Symptom_3,Symptom_4,Symptom_5,Symptom_6,Symptom_7,Symptom_8,Symptom_9,Symptom_10,Symptom_11,Symptom_12,Symptom_13,Symptom_14,Symptom_15,Symptom_16,Symptom_17
count,4920.000000,4920.000000,4920.000000,4920.000000,4920.000000,4920.000000,4920.000000,4920.000000,4920.000000,4920.000000,4920.000000,4920.000000,4920.000000,4920.000000,4920.000000,4920.000000,4920.000000,4920.000000
mean,20.000000,18.095122,26.941463,27.067073,26.698780,22.830488,21.917073,19.010976,16.219512,18.135366,17.981707,15.600000,10.071951,7.541463,3.835366,2.902439,2.917073,0.985366
std,11.833362,10.234807,13.968681,14.795179,15.523655,12.333713,10.610690,9.141491,7.067688,6.617353,5.668923,4.955275,2.502145,1.553906,0.699177,0.452943,0.439502,0.120095
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,10.000000,11.000000,15.000000,19.000000,13.000000,12.000000,13.000000,12.000000,11.000000,16.000000,18.000000,18.000000,11.000000,8.000000,4.000000,3.000000,3.000000,1.000000
50%,20.000000,15.000000,28.000000,24.000000,26.000000,23.000000,25.000000,26.000000,21.000000,22.000000,21.000000,18.000000,11.000000,8.000000,4.000000,3.000000,3.000000,1.000000
75%,30.000000,28.000000,42.000000,39.000000,40.000000,37.000000,32.000000,26.000000,21.000000,22.000000,21.000000,18.000000,11.000000,8.000000,4.000000,3.000000,3.000000,1.000000
max,40.000000,33.000000,47.000000,53.000000,50.000000,38.000000,32.000000,26.000000,21.000000,22.000000,21.000000,18.000000,11.000000,8.000000,4.000000,3.000000,3.000000,1.000000

,Disease,Symptom_1,Symptom_2,Symptom_3,Symptom_4,Symptom_5,Symptom_6,Symptom_7,Symptom_8,Symptom_9,Symptom_10,Symptom_11,Symptom_12,Symptom_13,Symptom_14,Symptom_15,Symptom_16,Symptom_17
0,15,33,35,35,11,38,32,26,21,22,21,18,11,8,4,3,3,1
1,15,24,27,18,50,38,32,26,21,22,21,18,11,8,4,3,3,1
2,15,33,27,18,50,38,32,26,21,22,21,18,11,8,4,3,3,1
3,15,33,35,18,50,38,32,26,21,22,21,18,11,8,4,3,3,1
4,15,33,35,35,50,38,32,26,21,22,21,18,11,8,4,3,3,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4915,0,28,17,33,38,22,29,26,21,22,21,18,11,8,4,3,3,1
4916,2,24,31,3,35,38,32,26,21,22,21,18,11,8,4,3,3,1
4917,38,4,4,22,7,38,32,26,21,22,21,18,11,8,4,3,3,1
4918,35,24,20,42,36,27,15,26,21,22,21,18,11,8,4,3,3,1
4919,27,24,18,4,33,35,32,26,21,22,21,18,11,8,4,3,3,1

numeric_df.shape=(4920, 18)

In [3]:
# make the model and train it based on the dataset using KNeighborsClassifier from sklearn
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split

X, y = numeric_df.drop('Disease', axis=1), numeric_df['Disease']
X_train, X_test, y_train, y_test = train_test_split(
 X, y, test_size=0.33, random_state=42)

# it shouldn't work like this WTF
KNN = KNeighborsClassifier(n_neighbors=1)

model = KNN.fit(X_train, y_train)

from sklearn.metrics import accuracy_score
# check the accuracy of the model
print(f'accuracy={accuracy_score(y_test, model.predict(X_test))}')

accuracy=1.0

In [4]:
input_df = pd.DataFrame(columns=X_test.columns)
# itching, headache, nodal_skin_eruptions, null, null, null, ...
input_df.loc[1] = [33, 17, 35, 50, 38, 32, 26, 21, 22, 21, 18, 11, 8, 4, 3, 3, 1]
input_df

,Symptom_1,Symptom_2,Symptom_3,Symptom_4,Symptom_5,Symptom_6,Symptom_7,Symptom_8,Symptom_9,Symptom_10,Symptom_11,Symptom_12,Symptom_13,Symptom_14,Symptom_15,Symptom_16,Symptom_17
1,33,17,35,50,38,32,26,21,22,21,18,11,8,4,3,3,1

In [5]:
model.predict(input_df) # got Impetigo and not Fungal infection

array([27])